[tools]
rust = { version = "1.86.0" }

[tasks.build]
dir = "."
depends = ["build:wasm"]
depends_post = ["generate:checksum"]
run = [
	"mv ./target/wasm32-unknown-unknown/release/link.wasm ./output/plugin.wasm",
]

[tasks."build:wasm"]
dir = "."
run = "cargo build --release --target wasm32-unknown-unknown"

[tasks."generate:checksum"]
dir = "output"
run = "sha256sum -b plugin.wasm | cut -d' ' -f1 | tr -d '\n' > plugin.wasm.sha256"

[tasks."update:submodules"]
dir = "."
run = [
	"git submodule update --init --recursive",
	"git submodule foreach git pull origin master",
]
